# fly.toml app configuration file generated for pricebook-asmp-server on 2025-09-25T16:31:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pricebook-asmp-server'
primary_region = 'yyz'

[build]

[env]
  DB_FILE = "/data/asmp.db"

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 49876
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[checks]]
  name = "healthz"
  type = "http"
  port = 49876
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/healthz"
